#Archivo: SCRIPT06.SQL 
/*Descripción: Sirve para realizar las inserciones una a una de los datos ejemplo del CIT de la entidad TUTOR en la tabla 
TUTOR especificando el valor de cada uno de sus campos.*/
USE ESCUELA;
INSERT INTO TUTOR VALUES ('Jorge','CELIS','ROJO',1234567); 
INSERT INTO TUTOR VALUES ('José','HERRERA','CALDERON',1234568); 
INSERT INTO TUTOR VALUES ('Luis','HERNANDEZ','RODRIGUEZ',1234569); 
INSERT INTO TUTOR VALUES ('Acosta','LOPEZ','DOMINGUEZ',1234570); 
INSERT INTO TUTOR VALUES ('Francisco','SANCHEZ','BOJALILÂ ',1234571); 
INSERT INTO TUTOR VALUES ('Luis','CASTANIEDA','GONZALEZ',1234572); 
INSERT INTO TUTOR VALUES ('Luis','RAMIREZ','ALVAREZ',1234573); 
INSERT INTO TUTOR VALUES ('Altriste','FUNES','SANCHEZ',1234574); 
INSERT INTO TUTOR VALUES ('Alcoverde','LACYÂ ','SOTO',1234575); 
INSERT INTO TUTOR VALUES ('Josse','BARRERA','URBINA',1234576); 
INSERT INTO TUTOR VALUES ('Almogabar','CHAN','NIETOÂ ',1234577); 
INSERT INTO TUTOR VALUES ('Jose','ISORDIAÂ ','GUTIERREZ',1234578); 
INSERT INTO TUTOR VALUES ('Diego','ZAJGLA','CAMPILLO',1234579); 
INSERT INTO TUTOR VALUES ('Fernando','DEHESA','TERESA',1234580); 
INSERT INTO TUTOR VALUES ('David','BELTRAN','BAEZA',1234581); 
INSERT INTO TUTOR VALUES ('Ricardo','ROSALES','MAULEN',1234582); 
INSERT INTO TUTOR VALUES ('Eusebio','CARMEN','CARMEN',1234583); 
INSERT INTO TUTOR VALUES ('Sebastian','GUADALAJARA','NARRO',1234584); 
INSERT INTO TUTOR VALUES ('Armando','ROJO','MONGE',1234585); 
INSERT INTO TUTOR VALUES ('Alvaro','CARNEVALE','MALACARA',1234586); 