#Archivo: SCRIPT04.SQL 
#Descripción: Sirve para crear a la tabla CALIFICACION. 
USE ESCUELA;
CREATE TABLE CALIFICACION ( 
	NSerial VARCHAR(18) NOT NULL, 
	Nota FLOAT(2) NOT NULL, 
	Fecha DATE NOT NULL, 
	DAlumno VARCHAR(20) NOT NULL, 
	PRIMARY KEY(NSerial), 
	FOREIGN KEY (DAlumno)REFERENCES ALUMNO(CURP) 
); 